### ISSUE TITLE
CSSのアンコメントに失敗する

### ISSUE THREAD

**Issue by sys9kdr** [emonkak/vim-operator-comment#1]
CSSをコメントアウトしようとすると下記のように、
スラッシュが残ってしまいます。

``` CSS
/*a{
color: red
}*/
```

↓

``` CSS
a{
color: red
}/
```
